version: '3.8'

services:
  mysql1:
    image: mysql:latest
    container_name: inventory-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
      MYSQL_USER: inventory
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-1:/var/lib/mysql

  mysql2:
    image: mysql:latest
    container_name: order-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
      MYSQL_USER: order
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-2:/var/lib/mysql
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db


volumes:
  mysql-data-1:
  mysql-data-2:
  dbdata6:
